### ISSUE TITLE
Twitter の取得に失敗

### ISSUE THREAD

**Issue by 0xBADDCAFE** [supermomonga/MoEmbed#104]
https://gist.github.com/raa0121/b9b31698db547ceca34dcfdabe5ccc92
https://github.com/supermomonga/MoEmbed/blob/master/MoEmbed.Twitter/TwitterMetadata.cs#L132

ついに API 失効？

**Comment by raa0121** [comment]
一旦別KEYで取得できるようにした。
何か手を考えたほうがいいかもしれない

**Comment by 0xBADDCAFE** [comment]
oEmbed ベースでの取得の実装に切り替わったのでクローズ
https://github.com/supermomonga/MoEmbed/commit/d5d5507418bdc9cddf3f64ecfc4d986482a70590
