### ISSUE TITLE
Visual Studio氏...でビルドが失敗する

### ISSUE THREAD

**Issue by pgrho** [supermomonga/MoEmbed#12]
![image](https://user-images.githubusercontent.com/18061424/28750316-743bf1a2-7521-11e7-963d-7aa53f5466ad.png)

**Comment by supermomonga** [comment]
https://developercommunity.visualstudio.com/content/problem/15861/unable-to-build-solution-after-upgrading-to-the-la.html

**Comment by supermomonga** [comment]
>Right click on the solution, disable "Lightweight Solution Load" then reload the solution. It surely will impact the loading time, but it worked for me.
>
>,
>Try to right click on the solution, and then disable the "Lightweight Solution Load", re-load your solution. It works for me.

**Comment by supermomonga** [comment]
Workaround っぽいのはあった

**Comment by pgrho** [comment]
oh..
