### ISSUE TITLE
プロジェクトの分割

### ISSUE THREAD

**Issue by pgrho** [supermomonga/MoEmbed#6]
コア、サービス別ハンドラー、Webアプリに分けるべきでは。

* MoEmbed.Core (NuGetパッケージ化)
    *  IHandler、EmbedObject、汎用ハンドラー

* MoEmbed.Twitter (NuGetパッケージ化)
    * TwitterHandler

* MoEmbed.App (別リポジトリ？)
    * モ氏が構成したアプリのインスタンス。
    * サービスで使用するハンドラーをコア部分に登録してWebアプリ起動

.NET CoreのコンフィギュレーションビルダーでIHandlerを構成させてもいいかも。
個人的な趣味としてはXAMLでDIだけど。

**Comment by supermomonga** [comment]
やるぞ〜
