### ISSUE TITLE
raw resource へのアクセス抑制

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/MoEmbed#63]
特に動画ファイルは読み込みたくない

まずHEADリクエストだけ送って、レスポンスヘッダのContent-Typeによっては再度GETリクエストを送る？

**Comment by pgrho** [comment]
```
class UnknownMetadata {
    protected virtual bool IsTextUrl(Uri url)
        => Regex.IsMatch(url.ToString(), @"\.(html?|txt)");
}
```

とか作ってGETかHEADか変えるとか????
.txtにアクセスする意味があるのかは知らんけど

`UnknownMetadata`派生型は決まった`Url`しか相手にしないので全部`true`にする感じ。あと`HttpClientHandler`かなんかでレスポンスサイズの制限できないのかな

**Comment by supermomonga** [comment]
しかしどうしてもURLだけだと確実に判断できないので、どんなURLにもまずはHEADリクエスト送るのがいいのかな〜

**Comment by pgrho** [comment]
`HttpClient`でリクエスト送るときに`HttpCompletionOption.ResponseHeadersRead`を指定するとヘッダーが返ってきた時点で処理できるので、`MoEmbed`的には`HEAD`とそんな変わらない感じになるかなー。

相手先サーバーの負荷は知らぬ

**Comment by supermomonga** [comment]
よさそう
相手先サーバー的にはコネクション早く切ってほしいだろうけど
