### ISSUE TITLE
Twitter が展開されない時がある

### ISSUE THREAD

**Issue by ryunix** [supermomonga/MoEmbed#78]
Twitter が展開されない時がある。  
細かい条件は不明ですが、特定ツイートの問題ではなさそう。  

1.  https://twitter.com/kayyyma/status/915935073165119490

少し前に貼った時に展開されなかったツイート。  
先程貼り直したところ展開された。  

2. https://twitter.com/Any512/status/917329362352988160

先程貼った時に展開されなかったツイート。  
そのすぐ後に貼り直したが展開されなかった。

**Comment by pgrho** [comment]
現状のエラーハンドリングは

- URLのフェッチに失敗した場合、共通部分では単に例外発生時の処理を行う
- 実際には各`Metadata`の内部でタスク(取得結果or例外)がキャッシュされる
- リトライが実装されているのは`UnknownMetadata`(汎用処理)と`AmazonMetadata`だけ
- `UnknownMetadata`以外はプロセスが再起動されるまでタスクを保持する (実際の設定は@supermomongaに聞いてください)
- `UnknownMetadata`はエラーが発生すると一定回数リトライし、全部失敗した場合は一定時間タスクを保持する

なので実装通りの動作にはなっていますね。タスクのキャッシュはあくまで各`Metadata`型が自主的に行っているという体の仕様なので、現状だと全`Metadata`型にリトライを組み込むのが正解になる。

**Comment by ryunix** [comment]
なるほど、ありがとうございます... が、私はよく分からないので後はも氏に任せる所存です (このIssueはも氏に促されて作成しました)。

**Comment by ryunix** [comment]
対応ありがとうございました。
